/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ToUpperExample */

#ifndef _Included_ToUpperExample
#define _Included_ToUpperExample
#ifdef __cplusplus
extern "C" {
#endif
#undef ToUpperExample_BUFSZ
#define ToUpperExample_BUFSZ 80L
/*
 * Class:     ToUpperExample
 * Method:    toUpper
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_ToUpperExample_toUpper
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
